fixed #154 unit test
mdl29/scratchy pull request #160
Opened 2021-05-09 14:13 UTC by Draeggon

[linked issue](https://github.com/mdl29/scratchy/issues/154)
the ressource: [pytest](https://docs.pytest.org/en/latest/) and [tavern](https://taverntesting.github.io/)

2021-05-09 20:05 UTC, Benvii requested changes
Missing stuff : 

- [x]  Add Tavern to the dependencies (requirements.txt file)
- [ ]  Documentation in server/README.md on how to run the tests

Errors : 
- Got this ugly warning when running tests, do you have the same one ? 
![erreur](https://user-images.githubusercontent.com/1092728/117585010-77a7a280-b110-11eb-99b7-52dc04335664.png)

2021-05-09 20:05 UTC, Benvii commented on server/scratchy_server/test/test_message.tavern.yaml
> +  - name: Post a room
Wording can be improve `Creating a room`

2021-05-09 20:05 UTC, Benvii commented on server/scratchy_server/test/test_message.tavern.yaml
> +      status_code: 200
It's already the default value [according to the documentation](status_code), you can remove it to make the yaml cleaner and only specify it when needed.

2021-05-09 20:36 UTC, Draeggon commented on server/scratchy_server/model/roomModel.py
> +    users = ma.fields.List(ma.fields.Str())
because when we store info we store it in str type so it caused issue

2021-05-12 19:35 UTC, Benvii commented on server/scratchy_server/model/roomModel.py
> +    users = ma.fields.List(ma.fields.Str())
What was the issue ?

2021-05-12 20:31 UTC, Draeggon commented on server/scratchy_server/model/roomModel.py
> +    users = ma.fields.List(ma.fields.Str())
we don't convert the id from str type to object id typ (idk if it is possible maybe create a ticket) so we store str type and it need to be str type

2021-05-15 13:05 UTC, landerneRPi commented on server/README.md
> +## how to run unitary test
This is integration test.
Please, could you rename this title in the documentation.

2021-05-15 13:15 UTC, landerneRPi submitted a review, later dismissed

2021-05-15 14:30 UTC, Benvii requested changes

2021-05-15 14:30 UTC, Benvii commented on server/scratchy_server/test/test_room.tavern.yaml
> +        id: !re_fullmatch "[0-9a-f]{24}"  # the regex check if id is an objectId
Use reference for id to define it only once

2021-05-15 14:41 UTC, landerneRPi approved these changes

2021-05-15 14:45 UTC, Benvii approved these changes

2021-05-15 14:57 UTC, merged