172 add handling of mongoengine.errors.validation error
mdl29/scratchy pull request #173
Opened 2021-05-21 21:20 UTC by Draeggon

2021-05-21 21:23 UTC, Draeggon commented
for now only the rooms are done i wait for your return before doing the other res

2021-05-23 20:00 UTC, Benvii requested changes
Try to use a MethodView decorator instead of calling it in each resource should be easier to integrate on all resources.

2021-05-24 20:44 UTC, Draeggon commented on server/scratchy_server/resources/roomres.py
> +        return func.get(RoomModel, roomId)
i don't really understand the doc could you make a more understandable example ?

2021-05-29 13:22 UTC, Benvii requested changes
Add this docator to all ressources.

2021-05-29 13:22 UTC, Benvii commented on server/scratchy_server/filters/mongoexception.py
> +def validation(func): # not entirely satisfied by the name, hoping someone will find a better one
Rename `func` with `ressource_method`.
Add pydoc to explain it should be use to wrappe a MethodView method.

2021-05-29 13:22 UTC, Benvii commented on server/scratchy_server/filters/mongoexception.py
> +    def new_func(*args, **kwargs):
Rename to `mongo_safe_ressource_method`

2021-05-29 16:09 UTC, closed without merging