183 retreive all user
mdl29/scratchy pull request #185
Opened 2021-05-22 21:14 UTC by Draeggon

fixes #183

2021-05-22 21:15 UTC, Draeggon commented
all users integration would be too tedious to do since they would break everything when they failed we need to have a dockerfile before implementing them or make pseudo not unique

2021-05-23 20:19 UTC, Benvii requested changes

2021-05-23 20:19 UTC, Benvii commented on server/scratchy_server/resources/userres.py
> +    @doc(tags=['AllUser'])
Actually there is no need to use a new tag, it's relating to the user resource it should be visible in the user section of the swagger.

I've tested, replace `AllUser` by `User` it works like a charm and it's easier to read it in the swagger UI also :
![UserTag](https://user-images.githubusercontent.com/1092728/119275291-76986a00-bc14-11eb-8922-f1a1eb49777b.png)

2021-05-24 19:19 UTC, Benvii approved these changes

2021-05-24 19:19 UTC, merged