143 [back] Configure logging using a file in server directory
mdl29/scratchy pull request #241
Opened 2021-07-22 19:34 UTC by landerneRPi

Add logging configuration using  external file.

2021-07-22 19:41 UTC, Draeggon commented
shouldn't we use
```py
logging.config.fileConfig(fname)
```
from https://docs.python.org/3/library/logging.config.html

2021-08-13 12:57 UTC, Benvii requested changes
Problem with logging, migth be the version ? Can you check please.

2021-08-13 12:57 UTC, Benvii commented on server/scratchy_server/app.py
> +logging.config.dictConfig(config_logging)
Got an error here : 
```

    File "/home/benjamin/Documents/MDL/LPH/repo/scratchy-1/server/scratchy_server/app.py", line 20, in <module>

    logging.config.dictConfig(config_logging)

    AttributeError: module 'logging' has no attribute 'config'
```


When I test logging in a python shell I got this version : 
```
╰─$ python                 
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.c
logging.captureWarnings(  logging.collections       logging.critical(         logging.currentframe(     
>>> logging.c
logging.captureWarnings(  logging.collections       logging.critical(         logging.currentframe(     
>>> logging.__version__
'0.5.1.2'
>>> logging.config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'logging' has no attribute 'config'
```

2021-08-13 14:03 UTC, Benvii submitted a review, later dismissed

2021-08-13 14:11 UTC, Benvii approved these changes

2021-08-13 14:11 UTC, merged