44 get all rooms
mdl29/scratchy pull request #49
Opened 2021-04-16 15:16 UTC by landerneRPi

2021-04-16 15:21 UTC, Draeggon commented on server/scratchy_server/app.py
> +api.add_resource(RoomsRes, '/api/room', '/api/room')
J'ai vomi

2021-04-16 15:22 UTC, Draeggon requested changes

2021-04-16 15:22 UTC, Draeggon commented on server/scratchy_server/app.py
> +api.add_resource(RoomsRes, '/api/room', '/api/room')
J'ai vomi

2021-04-16 15:25 UTC, landerneRPi commented on server/scratchy_server/app.py
> +api.add_resource(RoomsRes, '/api/room', '/api/room')
miam

2021-04-16 15:26 UTC, ritorizo requested changes
non

2021-04-17 12:26 UTC, Draeggon approved these changes

2021-04-17 12:44 UTC, Benvii approved these changes

2021-04-17 12:46 UTC, merged