Resolves #22 [Doc] Better read me
mdl29/scratchy pull request #84
Opened 2021-04-24 13:19 UTC by yannis-mlgrn

2021-04-24 15:00 UTC, Benvii requested changes

2021-04-24 15:00 UTC, Benvii commented on README.md
> + - 📂 Backend documentation's directory is [here]("doc/backend")
No `"` needed

2021-04-24 15:00 UTC, Benvii commented on doc/frontend/frontend.md
> +
Add : Open webbrowser at http://localhost:5000

2021-04-24 15:06 UTC, Draeggon submitted a review, later dismissed
there aren't the last update of the server/readme.md file in the new file doc/backend/API-documentation

2021-04-24 15:08 UTC, Benvii approved these changes

2021-04-24 15:08 UTC, Benvii submitted a review, later dismissed

2021-04-24 15:16 UTC, landerneRPi requested changes
Récupère les modifs de Noam. pour insérer les commande curl PUT dans le server/README.md

2021-04-24 16:28 UTC, landerneRPi approved these changes

2021-04-24 16:29 UTC, landerneRPi approved these changes

2021-04-24 16:29 UTC, landerneRPi approved these changes

2021-04-24 16:30 UTC, Draeggon approved these changes

2021-04-24 16:30 UTC, merged

2021-04-25 20:02 UTC, Benvii reviewed
Changes are ok :+1: